let products=[
    { 
     name: 'Bread', 
     category: 'Pantry', 
     price: 1.99, 
     tag:'Bread.jpg',
     salesTax: false, 
     inCart: 0,
     id: 1,
 },
    { 
     name: 'Dog Food', 
     category: 'Pet', 
     price: 45.00,
     tag:'DOg.jpg', 
     salesTax: true, 
     inCart: 0,
     id: 2,
 },
    { 
     name: 'Ground Pork', 
     category: 'Meat', 
     price: 14.99,
     tag:'Beeef.jpg', 
     salesTax: false, 
     inCart: 0,
     id: 3,
 },
    { 
     name: 'Milk', 
     category: 'Dairy', 
     price: 2.99, 
     tag:'ilk.jpg',
     salesTax: false, 
     inCart: 0,
     id: 4,
 },
 {
     name: 'Eggs',
     category: 'Protein',
     price: 2.59,
     tag:'Eggs.jpg',
     salesTax: false,
     inCart: 0,
     id: 5,
 },
 {
     name: 'Bananas',
     category: 'Produce',
     price: 3.79,
     tag: 'Bana.jpg',
     salesTax: false,
     inCart: 0,
     id: 6,
 },
 {
     name: 'Sushi',
     category: 'Protein',
     price: 8.99,
     tag:'Sush.jpg',
     salesTax: true,
     inCart: 0,
     id: 7,
 },
 {
     name: 'Yogurt',
     category: 'Dairy',
     price: 1.06,
     tag:'Yop.webp',
     salesTax: false,
     inCart: 0,
     id: 8,
 },
 {
     name: 'Tofu',
     category:'Protein',
     price: 2.48,
     tag:'tofu_image.png',
     salesTax: false,
     inCart: 0,
     id: 9,
 },
 {
     name: 'Carrots',
     category: 'Produce',
     price: 0.79,
     tag:'carrots_image.png',
     salesTax: false,
     inCart: 0,
     id: 10,
 }
 
 ]